sudo: false
matrix:
  include:
    - env: PLATFORM=ios-9.3
      os: osx
      osx_image: xcode7.3
      language: node_js
      node_js: "4.2"
    - env: PLATFORM=ios-10.0
      os: osx
      osx_image: xcode7.3
      language: node_js
      node_js: "4.2"
    - env: PLATFORM=android-4.4
      os: linux
      language: android
      node_js: "4.2"
      jdk: oraclejdk8
      android:
        components:
          - tools
          - tools
    - env: PLATFORM=android-5.1
      os: linux
      language: android
      node_js: "4.2"
      jdk: oraclejdk8
      android:
        components:
          - tools
          - tools
    - env: PLATFORM=android-6.0
      os: linux
      language: android
      node_js: "4.2"
      jdk: oraclejdk8
      android:
        components:
          - tools
          - tools
    - env: PLATFORM=android-7.0
      os: linux
      language: android
      node_js: "4.2"
      jdk: oraclejdk8
      android:
        components:
          - tools
          - tools
before_install:
  - npm cache clean -f
  - npm install -g n
  - node --version
  - if [[ "$PLATFORM" =~ android ]]; then gradle --version; fi
  - if [[ "$PLATFORM" =~ ios ]]; then npm install -g ios-deploy; fi
  - if [[ "$PLATFORM" =~ android ]]; then echo y | android update sdk -u --filter android-22,android-23,android-24,android-25; fi
  - git clone https://github.com/apache/cordova-paramedic /tmp/paramedic && pushd /tmp/paramedic && npm install && popd
  - npm install -g cordova
install:
  - npm install
script:
  - echo $SAUCE_USER
  - echo $SAUCE_ACCESS_KEY
  - npm test
  - node /tmp/paramedic/main.js --config pr/$PLATFORM --plugin $(pwd) --shouldUseSauce --buildName travis-plugin-device-$TRAVIS_BUILD_NUMBER

  